name: probForecETS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - matplotlib=3.1.2
  - numpy=1.18.1
  - pandas=0.25.3
  - pip=19.3.1
  - python=3.7.6
  - pytorch=1.4.0
  - scikit-learn=0.20.3
  - scikit-optimize=0.5.2
  - skorch=0.7.0
  - torchvision=0.5.0
  - pip:
    - gpytorch==1.0.1
    - workalendar==8.0.2

