name: probForecETS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pillow=7.0.0
  - pip=19.3.1
  - pycparser=2.19
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2019.3
  - qt=5.9.7
  - scikit-learn=0.20.3
  - scikit-optimize=0.5.2
  - scipy=1.3.2
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - skorch=0.7.0
  - sqlite=3.30.1
  - tabulate=0.8.3
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.3
  - tqdm=4.41.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - gpytorch==1.0.1
    - jplephem==2.12
    - lunardate==0.2.0
    - pycalverter==1.6.1
    - pyluach==1.0.1
    - sgp4==1.4
    - skyfield==1.16
    - skyfield-data==0.1.0
    - workalendar==8.0.2

